blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: https://github.com/Heartlytics/Heartlytics/security/policy
    about: Please report security issues through our coordinated disclosure program.
